Models/Payslip/ItemTuple.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EchoPay.Models.Payslip
{
    public class ItemTuple
    {
        public int PresetItemId { get; set; }
        public double ItemAmount { get; set; }
    }
}

Models/Payslip/PayrollHistoryViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EchoPay.Models.Payslip
{
    public class PayrollHistoryViewModel
    {
        public PayrollSummaryViewModel PayrollSummaryViewModel { get; set; }
        public IEnumerable<SelectListItem> PastPayroll { get; set; }

        [Display(Name ="Select Year/Month")]
        public string SelectedPayroll { get; set; }
        public List<string> PayslipHTML { get; set; }
        public List<int> PayslipStaffSequence { get; set; }
    }
}

Models/Payslip/PayrollSummaryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EchoPay.Models.Payslip
{
    public class PayrollSummaryViewModel
    {
        public List<PayslipViewModel> PayslipViewModels { get; set; }
        public Data.Company Company { get; set; }
        public double TotalEmployeeNetPay { get; set; }
        public double TotalEPF_Payment { get; set; }
        public double TotalSOCSO_Payment { get; set; }
    }
}

Models/Payslip/PayslipViewModel.cs
using EchoPay.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EchoPay.Models.Payslip
{
    public class PayslipViewModel
    {
        public int Id { get; set; }
        public int StaffId { get; set; }
        public Data.Company Company { get; set; }
        public Data.Staff Staff { get; set; }
        public DateTime Date { get; set; }
        public double BaseSalary { get; set; }
        public double NetSalary { get; set; }
        public double InEPF_EmployerRate { get; set; }
        public double InEPF_EmployeeRate { get; set; }
        public double OutEPF_EmployerAmount { get; set; }
        public double OutEPF_EmployeeAmount { get; set; }
        public double OutSOCSO_EmployerAmount { get; set; }
        public double OutSOCSO_EmployeeAmount { get; set; }
        public List<PayslipItem> AddItems { get; set; }
        public List<PayslipItem> DeductItems { get; set; }
        public double VariablePay { get; set; }
        public double VariableDeduction { get; set; }

        public List<ItemTuple> ExistingItems { get; set; }

        // for user input
        [Display(Name = "New Item")]
        public int NewItemId { get; set; } = 0;

        [Display(Name = "Amount")]
        public double NewItemAmount { get; set; } = 0.0;

        // select list item
        public IEnumerable<SelectListItem> AvailablePayrollItems { get; set; }
    }
}

Models/Payslip/PresetPayslipItemViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EchoPay.Models.Payslip
{
    public class PresetPayslipItemViewModel : Data.PresetPayslipItem
    {
        // select list
        public IEnumerable<SelectListItem> DirectionList { get; set; }
        public IEnumerable<SelectListItem> EPF_ApplicableList { get; set; }
        public IEnumerable<SelectListItem> SOCSO_ApplicableList { get; set; }
    }
}

Models/Payslip/ReportSingleStaffViewModel.cs
using EchoPay.Models.Staff;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EchoPay.Models.Payslip
{
    public class ReportSingleStaffViewModel
    {
        public StaffViewModel StaffViewModel { get; set; }
        public IEnumerable<SelectListItem> PastPayroll { get; set; }
        [Display(Name = "Select Year/Month")]
        public string SelectedPayroll { get; set; }
        public List<PayslipViewModel> PayslipViewModels { get; set; }
    }
}

Models/Staff/AdminAttendancePageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EchoPay.Models.Staff
{
    public class AdminAttendancePageViewModel
    {
        public ICollection<StaffViewModel> StaffViewModels { get; set; }
        // others add later
    }
}

Models/Staff/AdminStaffPageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EchoPay.Models.Staff
{
    public class AdminStaffPageViewModel
    {
        public CreateStaffCommand CreateStaffCommand { get; set; }
        public ICollection<StaffViewModel> StaffViewModels { get; set; }
    }
}

Models/Staff/AttendanceViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EchoPay.Models.Staff
{
    public class AttendanceViewModel
    {
        public int Id { get; set; }
        public int StaffId { get; set; }
        public string StaffName { get; set; }
        public DateTime Date { get; set; }
        public DateTime TimeIn { get; set; }
        public DateTime TimeOut { get; set; }

        [Required]
        [Display(Name = "Attended")]
        public int AttendedFlag { get; set; } = 0;
    }
}

Models/Staff/CreateAttendanceCommand.cs
namespace EchoPay.Models.Staff
{
    public class CreateAttendanceCommand : AttendanceViewModel
    {
        // Id from AttendanceViewModel is not needed
        public Data.Attendance ToAttendance()
        {
            return new Data.Attendance
            {
                StaffId = StaffId,
                Date = Date,
                TimeIn = TimeIn,
                TimeOut = TimeOut
            };
        }
    }
}

Models/Staff/CreatePositionCommand.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EchoPay.Models.Staff
{
    public class CreatePositionCommand : EditPositionBase
    {
        public Data.Position ToPosition()
        {
            return new Data.Position
            {
                Name = Name
            };
        }
    }
}

Models/Staff/CreateStaffCommand.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace EchoPay.Models.Staff
{
    public class CreateStaffCommand : EditStaffBase
    {
        // send email to staff to set password
        [Required]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email Address")]
        public string Email { get; set; }

        // 1 = send email, 2 = bind this account to self
        public int CreateStaffOption { get; set; } = 2;
        [Display(Name = "Choose your action")]
        public IEnumerable<SelectListItem> CreateStaffOptionList { get; set; }


        public Data.Staff ToStaff()
        {
            return new Data.Staff
            {
                ICNo = ICNo,
                UserId = UserId,
                Name = Name,
                PositionId = PositionId,
                ContactNo = ContactNo,
                Address = new Data.Address
                {
                    StreetAddress = StreetAddress,
                    City = City,
                    PostalCode = PostalCode,
                    StateId = StateId,
                },
                NationalityId = NationalityId,
                AdmissionDate = AdmissionDate,
                DOB = DOB,
                SalaryAmount = SalaryAmount,
                EPF_No = EPF_No,
                EPF_StatusId = EPF_StatusId,
                EPF_EmployerRate = EPF_EmployerRate,
                EPF_EmployeeRate = EPF_EmployeeRate,
                SOCSO_CategoryId = SOCSO_CategoryId
            };
        }
    }
}

Controllers/PDFController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SelectPdf;
using System.IO.Compression;
using System.Net;
using EchoPay.Data;
using EchoPay.Services;

namespace EchoPay.Controllers
{
    public class PDFController : Controller
    {
        public string[] PayslipOuterHTML =
            {
                "<!DOCTYPE html> <html lang=\"en\"> <head> <meta charset=\"utf-8\" /><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" /><link rel=\"stylesheet\" type=\"text/css\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons\" /><link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css\"><link href=\"/dashboard-assets/css/material-dashboard.css?v=2.1.2\" rel=\"stylesheet\" /> <title> EchoPay </title> <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' /> </head> <body style=\"background-color: #ffffff; scrollbar-width: none;-ms-overflow-style: none;overflow:hidden;\">",
                "</body></html>"
            };
        private readonly IEmailSender _emailSender;
        private readonly StaffService _staffService;

        public PDFController(StaffService staffService, IEmailSender emailSender)
        {
            _emailSender = emailSender;
            _staffService = staffService;
        }

        public IActionResult GeneratePDF(string HTMLcontent)
        {
            PdfDocument doc = GetPayslipFromHTML(HTMLcontent);

            // create memory stream to save PDF
            MemoryStream pdfStream = new MemoryStream();

            // save pdf document into a MemoryStream
            doc.Save(pdfStream);
            // reset stream position
            pdfStream.Position = 0;
            // close pdf document
            doc.Close();

            return new FileStreamResult(pdfStream, "application/pdf");
        }

        public IActionResult DownloadList(string[] PayslipHTML, int[] PayslipStaffSequence)
        {
            using (var memoryStream = new MemoryStream())
            {
                using (var ziparchive = new ZipArchive(memoryStream, ZipArchiveMode.Create, true))
                {
                    for (int i = 0; i < PayslipHTML.Length; i++)
                    {
                        var document = GetPayslipFromHTML(PayslipHTML[i]);
                        string name = _staffService.GetStaffById(PayslipStaffSequence[i]).Name;
                        AddToArchive(ziparchive, DateTime.Now.ToString("yyyy-MM-dd") + "_" + name + ".pdf", document.Save());
                    }
                }
                return File(memoryStream.ToArray(), "application/zip", "Attachments.zip");
            }
        }

        public IActionResult SendEmailToAll(string [] PayslipHTML, int[] PayslipStaffSequence)
        {
            if (PayslipHTML.Length != PayslipStaffSequence.Length)
            {
                throw new Exception("Why????");
            }

            for (int i = 0; i < PayslipHTML.Length; i++)
            {
                Staff toStaff = _staffService.GetStaffById(PayslipStaffSequence[i]);
                PdfDocument doc = GetPayslipFromHTML(PayslipHTML[i]);

                // create memory stream to save PDF
                MemoryStream pdfStream = new MemoryStream();

                // save pdf document into a MemoryStream
                doc.Save(pdfStream);
                // reset stream position
                pdfStream.Position = 0;

                _emailSender.Send(
                    toStaff.User.Email,
                    "Payslip",
                    "Download the payslip in attachment.",
                    pdfStream,
                    true);

                // close pdf document
                doc.Close();
            }

            return View();
        }

        public IActionResult SendEmailToAllAndDownload(string[] PayslipHTML, int[] PayslipStaffSequence)
        {
            if (PayslipHTML.Length != PayslipStaffSequence.Length)
            {
                throw new Exception("Why????");
            }
            List<byte[]> documents = new List<byte[]>();
            List<string> staffNames = new List<string>();

            for (int i = 0; i < PayslipHTML.Length; i++)
            {
                Staff toStaff = _staffService.GetStaffById(PayslipStaffSequence[i]);
                staffNames.Add(toStaff.Name);

                PdfDocument doc = GetPayslipFromHTML(PayslipHTML[i]);
                

                // create memory stream to save PDF
                MemoryStream pdfStream = new MemoryStream();

                // save pdf document into a MemoryStream
                doc.Save(pdfStream);
                // reset stream position
                pdfStream.Position = 0;
                documents.Add(pdfStream.ToArray());

                _emailSender.Send(
                    toStaff.User.Email,
                    "Payslip",
                    "Download the payslip in attachment.",
                    pdfStream,
                    true);

                // close pdf document
                doc.Close();
            }

            using (var memoryStream = new MemoryStream())
            {
                using (var ziparchive = new ZipArchive(memoryStream, ZipArchiveMode.Create, true))
                {
                    for (int i = 0; i < documents.Count; i++)
                    {
                        AddToArchive(ziparchive, DateTime.Now.ToString("yyyy-MM-dd")+ "_" + staffNames[i] + ".pdf", documents[i]);
                    }
                }
                return File(memoryStream.ToArray(), "application/zip", "Attachments.zip");
            }
        }



        private PdfDocument GetPayslipFromHTML(string html)
        {
            string root = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}";

            // instantiate a html to pdf converter object
            HtmlToPdf converter = new HtmlToPdf();

            string newHtml = PayslipOuterHTML[0] + html + PayslipOuterHTML[1];

            // set converter options
            converter.Options.PdfPageSize = PdfPageSize.A4;
            converter.Options.PdfPageOrientation = PdfPageOrientation.Portrait;
            converter.Options.MarginLeft = 10;
            converter.Options.MarginRight = 10;
            converter.Options.MarginTop = 20;
            converter.Options.MarginBottom = 20;

            converter.Options.WebPageWidth = 1024;
            converter.Options.WebPageHeight = 0;
            converter.Options.WebPageFixedSize = false;

            converter.Options.AutoFitWidth = HtmlToPdfPageFitMode.AutoFit;
            converter.Options.AutoFitHeight = HtmlToPdfPageFitMode.NoAdjustment;

            // create a new pdf document converting an url
            PdfDocument doc = converter.ConvertHtmlString(newHtml, root);
            return doc;
        }

        private void AddToArchive(ZipArchive ziparchive, string fileName, byte[] attach)
        {
            var zipEntry = ziparchive.CreateEntry(fileName, CompressionLevel.Optimal);
            using (var zipStream = zipEntry.Open())
            using (var streamIn = new MemoryStream(attach))
            {
                streamIn.CopyTo(zipStream);
            }
        }
    }
}

Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using EchoPay.Data;
using EchoPay.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Org.BouncyCastle.Math.EC.Rfc7748;

namespace EchoPay.Controllers
{
    [Authorize]
    public class StaffController : Controller
    {
        private readonly PayslipService _payslipService;
        private readonly AppDbContext _context;

        public StaffController(PayslipService payslipService, AppDbContext context)
        {
            _payslipService = payslipService;
            _context = context;
        }

        public IActionResult Index()
        {
            Data.Staff userStaff = _context.Staffs
                .Where(x => x.UserId == User.FindFirstValue(ClaimTypes.NameIdentifier))
                .FirstOrDefault();

            if (userStaff == null)
            {
                return RedirectToAction("Index", "Admin");
            }

            return RedirectToAction("Payslip");
        }

        public IActionResult Payslip()
        {

            Data.Staff userStaff = _context.Staffs
                .Where(x => x.UserId == User.FindFirstValue(ClaimTypes.NameIdentifier))
                .FirstOrDefault();

            if (userStaff == null)
            {
                return RedirectToAction("Index", "Admin");
            }

            int staffId = userStaff.Id;
            var model = _payslipService.GetSingleStaffReport(staffId);
            return View(model);
        }

        public IActionResult Report()
        {
            Data.Staff userStaff = _context.Staffs
                .Where(x => x.UserId == User.FindFirstValue(ClaimTypes.NameIdentifier))
                .FirstOrDefault();

            if (userStaff == null)
            {
                return RedirectToAction("Index", "Admin");
            }

            int staffId = userStaff.Id;
            var model = _payslipService.GetSingleStaffReport(staffId);
            return View(model);
        }
    }
}

Views/Staff/Payslip.cshtml
@model ReportSingleStaffViewModel
@{
    ViewData["Title"] = "Report";
    Layout = "_DashboardLayout";
}

<div class="container-fluid">
    <h4>Report of @Model.StaffViewModel.Name</h4>
    <div class="row">
        <div class="col-md-12">

            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title">Payslips</h4>
                </div>

                <div class="card-body">
                    <div id="typography">
                        @if (Model.PayslipViewModels != null)
                        {
                            <form method="post">
                                <div class="container-fluid mt-2">
                                    <div class="form-group">
                                        <label for="selectPayslip">Year/Month</label>
                                        <select class="form-control" data-style="btn btn-link" id="selectPayslip">
                                            @foreach (var payslip in Model.PayslipViewModels)
                                            {
                                                <option value="@payslip.Id">@payslip.Date.ToString("yyyy/MM")</option>
                                            }
                                        </select>
                                    </div>

                                    @foreach (var payslip in Model.PayslipViewModels)
                                    {
                                        @await Html.PartialAsync("_PartialPayslip.cshtml", payslip)
                                    }

                                    <input type="hidden" name="HTMLcontent" id="pdfInput" value="" />
                                    <button type="submit" asp-action="GeneratePDF" asp-controller="PDF" class="btn btn-primary" id="downloadSingle">Download PDF</button>

                                </div>

                            </form>
                        }
                        @if (Model.PayslipViewModels == null)
                        {
                            <div class="container-fluid mt-2">
                                <h4 class="card-title">No payslip found</h4>
                                <p class="card-category">
                                    Please wait for the coming payroll
                                </p>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




@section Scripts {
    <script>
        $(document).ready(() => {
            $('.singlePayslip').hide();
            // only show first element at first
            $('.singlePayslip').first().show();

            $('#selectPayslip').on('change', (x) => {
                const selectedPayslipId = $(x.target).val();
                console.log(selectedPayslipId);
                $('.singlePayslip').hide();
                $('.payslipId' + selectedPayslipId).show();
            });
        });


        // download single pdf
        $(document).ready(() => {
            $('#downloadSingle').on('click', (x) => {
                x.preventDefault();
                const selectedPayslipId = $('#selectPayslip').val();
                console.log(selectedPayslipId);
                const payslip = $('.payslipId' + selectedPayslipId)[0].outerHTML;
                console.log(payslip);
                $('#pdfInput').val(payslip);
                $('form').attr('action', '/PDF/GeneratePDF');
                $('form').attr('target', 'popup_pdf');
                $('form').on('submit', () => window.open('about:blank', 'popup_pdf', 'width=1000,height=720'));
                $('form').submit();

                $('form').attr('target', '_self');
            });
        });

    </script>
}

Views/Staff/Report.cshtml
@model ReportSingleStaffViewModel
@{
    ViewData["Title"] = "Report";
    Layout = "_DashboardLayout";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-danger">
                    <h4 class="card-title ">Summary Report</h4>
                    <p class="card-category">Summary of all payslips</p>
                </div>
                <div class="card-body">
                    @if (Model.PayslipViewModels != null)
                    {
                        <div class="table-responsive">
                            <table class="table">
                                <tr class=" text-primary">
                                    <th>Date</th>
                                    <th>Basic Salary</th>
                                    <th>Net Salary</th>
                                    <th>Variable Pay</th>
                                    <th>Variable Deduction</th>
                                    <th>EPF Contributed</th>
                                    <th>SOCSO Contributed</th>
                                </tr>
                                <tbody>
                                    @foreach (var payslip in Model.PayslipViewModels)
                                    {
                                        <tr>
                                            <td>@payslip.Date.ToString("yyyy-MM-dd")</td>
                                            <td>@payslip.BaseSalary.ToString("0.00")</td>
                                            <td>@payslip.NetSalary.ToString("0.00")</td>
                                            <td>@payslip.VariablePay.ToString("0.00")</td>
                                            <td>@payslip.VariableDeduction.ToString("0.00")</td>
                                            <td>@payslip.OutEPF_EmployeeAmount.ToString("0.00")</td>
                                            <td>@payslip.OutSOCSO_EmployeeAmount.ToString("0.00")</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>

                    }
                    @if (Model.PayslipViewModels == null)
                    {
                        <div class="container-fluid mt-2">
                            <h4 class="card-title">No payroll record found</h4>
                            <p class="card-category">
                                Report will be shown after first payroll submitted for this staff
                            </p>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Views/Staff/_PartialPayslip.cshtml
@model PayslipViewModel
    <div class="container singlePayslip @("payslipId" + Model.Id)" id="@Model.StaffId">
        <div class="row">
            <div class="col-4">
                <h4>Payslip</h4>
                <p class="my-0"><strong>@Model.Date.ToString("MMMM yyyy")</strong></p>
                <p class="my-0">Issue Date: @Model.Date.ToString("MMMM dd yyyy")</p>
            </div>
            <div class="col-4">
                <h4>Company</h4>
                <p class="my-0"><strong>@Model.Company.Name</strong></p>
                <p class="my-0">@Model.Company.Address.StreetAddress</p>
                <p class="my-0">@Model.Company.Address.City</p>
                <p class="my-0">@Model.Company.Address.PostalCode</p>
                <p class="my-0">@Model.Company.Address.State.Name</p>
            </div>
            <div class="col-4">
                <h4>Employee</h4>
                <p class="my-0"><strong>@Model.Staff.Name</strong></p>
                <p class="my-0">@Model.Staff.Position.Name</p>
                <p class="my-0">@Model.Staff.ICNo</p>
                <p class="my-0">@Model.Staff.EPF_No</p>
            </div>
        </div>
        <hr />
        <div class="table-responsive">
            <table class="table table-bordered ml-1 no-datatable" style="width: 95%;">
                <tr></tr>
                <tr>
                    <td colspan="1">Basic Salary:</td>
                    <td colspan="4" class="text-right">@Model.BaseSalary.ToString("0.00")</td>
                </tr>
                <tr>
                    <td colspan="1">Variable Pay:</td>
                    <td colspan="4" class="text-right">@Model.VariablePay.ToString("0.00")</td>
                </tr>

                @if (Model.AddItems.Count > 0)
                {
                    <tr>
                        <td colspan="1"></td>
                        <td colspan="2"><strong>Description</strong></td>
                        <td colspan="2" class="text-right"><strong>Amount</strong></td>
                    </tr>

                    @foreach (var item in Model.AddItems)
                    {
                        <tr>
                            <td colspan="1"></td>
                            <td colspan="2">@item.PresetPayslipItem.Name</td>
                            <td colspan="2" class="text-right">@item.Amount.ToString("0.00")</td>
                        </tr>
                    }
                }

                <tr>
                    <td colspan="1">Variable Deduction:</td>
                    <td colspan="4" class="text-right">@Model.VariableDeduction.ToString("0.00")</td>
                </tr>

                @if (Model.DeductItems.Count > 0)
                {
                    <tr>
                        <td colspan="1"></td>
                        <td colspan="2"><strong>Description</strong></td>
                        <td colspan="2" class="text-right"><strong>Amount</strong></td>
                    </tr>

                    @foreach (var item in Model.DeductItems)
                    {
                        <tr>
                            <td colspan="1"></td>
                            <td colspan="2">@item.PresetPayslipItem.Name</td>
                            <td colspan="2" class="text-right">@item.Amount.ToString("0.00")</td>
                        </tr>
                    }
                }

                <tr>
                    <td colspan="1">Statutory Contribution:</td>
                    <td colspan="4" class="text-right">(@((Model.OutEPF_EmployeeAmount + Model.OutSOCSO_EmployeeAmount).ToString("0.00"))</td>
                </tr>

                <tr>
                    <td colspan="1"><strong>Net Salary:</strong></td>
                    <td colspan="4" class="text-right">@(Model.NetSalary.ToString("0.00"))</td>
                </tr>

                <tr>
                    <td colspan="5"></td>
                </tr>

                <tr>
                    <td colspan="5"><strong>Statutory Contribution</strong></td>
                </tr>

                <tr>
                    <td colspan="1"></td>
                    <td colspan="1"><strong>Employer</strong></td>
                    <td colspan="1"><strong>Employee</strong></td>
                    <td colspan="2" class="text-right"><strong>Subtotal</strong></td>
                </tr>

                <tr>
                    <td colspan="1">&nbsp;&nbsp;EPF:</td>
                    <td colspan="1">@Model.OutEPF_EmployerAmount.ToString("0.00")</td>
                    <td colspan="1">@Model.OutEPF_EmployeeAmount.ToString("0.00")</td>
                    <td colspan="2" class="text-right">@((Model.OutEPF_EmployerAmount + Model.OutEPF_EmployeeAmount).ToString("0.00"))</td>
                </tr>

                <tr>
                    <td colspan="1">&nbsp;&nbsp;SOCSO:</td>
                    <td colspan="1">@Model.OutSOCSO_EmployerAmount.ToString("0.00")</td>
                    <td colspan="1">@Model.OutSOCSO_EmployeeAmount.ToString("0.00")</td>
                    <td colspan="2" class="text-right">@((Model.OutSOCSO_EmployerAmount + Model.OutSOCSO_EmployeeAmount).ToString("0.00"))</td>
                </tr>

                <tr>
                    <td colspan="1"><strong>Total:</strong></td>
                    <td colspan="1">@((Model.OutSOCSO_EmployerAmount + Model.OutEPF_EmployerAmount).ToString("0.00"))</td>
                    <td colspan="1">@((Model.OutSOCSO_EmployeeAmount + Model.OutEPF_EmployeeAmount).ToString("0.00"))</td>
                    <td colspan="2" class="text-right">@((Model.OutSOCSO_EmployerAmount + Model.OutEPF_EmployerAmount + Model.OutSOCSO_EmployeeAmount + Model.OutEPF_EmployeeAmount).ToString("0.00"))</td>
                </tr>
            </table>

        </div>
    </div>

Views/Staff/_PartialSidebar.cshtml
<div class="sidebar-wrapper">
    <ul class="nav">
        <li class="nav-item @(ViewContext.RouteData.Values["Action"].ToString() == "Payslip" ? "active" : "")">
            <a class="nav-link" asp-area="" asp-action="Payslip">
                <i class="material-icons">description</i>
                <p>Payslip</p>
            </a>
        </li>
        <li class="nav-item @(ViewContext.RouteData.Values["Action"].ToString() == "Report" ? "active" : "")">
            <a class="nav-link" asp-area="" asp-action="Report">
                <i class="material-icons">toc</i>
                <p>Report</p>
            </a>
        </li>
        @if (User.Claims.Where(x => x.Type == ClaimTypes.Role).FirstOrDefault().Value == "ADMIN")
        {
            <li class="nav-item">
                <a class="nav-link" asp-controller="Admin" asp-action="Index">
                    <i class="material-icons">cached</i>
                    <p>Switch to Admin Page</p>
                </a>
            </li>
        }
    </ul>
</div>